spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://192.168.56.30:5432/db_personas}
    username: ${DB_USERNAME:user_personas}
    password: ${DB_PASSWORD:password_secreta}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect